export const goods = [
    {id:0,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    
},{id:1,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
},{id:2,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
}, {id:3,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    
},   {id:4,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    
},    {id:5,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    
},    {id:6,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    
},    {id:7,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    
}, 
]