export const goods = [
    {id:0,
    title: `товар `,
    price: '1200 $',
    location: "Moscow",
    img:`../assets/voron.jpg`,
    description:"Nananananananananananananana Batman",
    
},{id:1,
    title: "товар 1",
    price: '1700 $',
    location: "Moscow",
    img:`https://www.google.com/url?sa=i&url=https%3A%2F%2Fgames.24tv.ua%2Fru%2Fminecraft-11-faktov-ob-igre-kotorye-dolzhen-novosti-ukrainy-i-mira_n1480495&psig=AOvVaw331smZM_QU_bi-P5BATa32&ust=1758610494910000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCLjG-ePk648DFQAAAAAdAAAAABAE`,
    description:"Nananananananananananananana Batman",
},{id:2,
    title: "товар 2",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
}, {id:3,
    title: "товар 3",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
},   {id:4,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
},    {id:5,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
},    {id:6,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
},    {id:7,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
}, 
]