import voron from '../assets/voron.jpg'

export const goods = [
    {id:0,
    title: `товар `,
    price: '1200 $',
    location: "Moscow",
    img: `${voron}`,
    description:"Nananananananananananananana Batman",
    
},{id:1,
    title: "товар 1",
    price: '1700 $',
    location: "Moscow",
    img:`${voron}`,
    description:"Nananananananananananananana Batman",
},{id:2,
    title: "товар 2",
    price: '1200 $',
    location: "Moscow",
    img:`${voron}`,
    description:"Nananananananananananananana Batman",
}, {id:3,
    title: "товар 3",
    price: '1200 $',
    location: "Moscow",
    img:`${voron}`,
    description:"Nananananananananananananana Batman",
    
},   {id:4,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
},    {id:5,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
},    {id:6,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
},    {id:7,
    title: "товар 1",
    price: '1200 $',
    location: "Moscow",
    img:`https://picsum.photos/seed/avito/1/400/300`,
    description:"Nananananananananananananana Batman",
    
}, 
]